site_name: 12321ua's notebook
site_url: https://au12321ua.github.io/note/
theme:
  name: material
nav:
  - 主页: index.md
  - 关于我: about.md
  - 课程笔记:
    - 计算机组成: 
      - chapter2: com_org/chapter2.md
      - chapter3: com_org/chapter3.md
    - ADS: 
      - 错题集: ads/ADS错题集.md