site_name: 12321ua's notebook
site_url: https://au12321ua.github.io/note/
theme:
  name: material
nav:
  - 主页: index.md
  - 关于我: about.md
  - 课程笔记:
    - 计算机网络: 
      - chapter3: com_org/chapter3.md
    - ADS: ADS.md